### ISSUE TITLE
Bug Report: something is wrong with the main 

### ISSUE THREAD

**Issue by ghost** [bbpanzu/FNF-Sunday#4]
this is the error 
export_sunday/release/macos/haxe/ApplicationMain.hx:299: characters 48-52 : Type not found : Main 

idk how to fix it

**Comment by bbpanzu** [comment]
did you rename the source folder? or change the project.xml in some way?

**Comment by ghost** [comment]
let me see

**Comment by ghost** [comment]
also hi i love your videos

**Comment by ghost** [comment]
i am trying to make your mod a mac version

**Comment by ghost** [comment]
and if you think im lying look at my [itch.io website https://jonnycat.itch.io/mods-mac-versions)
